### ISSUE TITLE
Maybe it's a legacy project

### ISSUE THREAD

**Issue by oak2** [sarkiroka/current-date#4]
Please, update the current date or rent me a time machine. Thanks.

**Comment by sarkiroka** [comment]
Oh no, the current time never will be legacy, it is always will be actual.
When I miss a commit, feel free to create pull request for the missing data

The time machine is very good idea, we will plan it into our roadmap, thanks!

**Comment by sarkiroka** [comment]
Hey @oak2 I saw your fork, but it was stopped. Can I help you to continue development of current-date project?
